name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-scan-publish:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Connexion au registre GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 4 : Construire l'image Docker
      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      # Étape 5 : Scanner l'image Docker avec Trivy
      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v0.11.1
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest

      # Étape 6 : Publier l'image Docker (si le scan réussit)
      - name: Push Docker Image
        if: success()  # Publier uniquement si toutes les étapes précédentes réussissent
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.sha }}
